--
-- Script was generated by Devart dbForge Studio for MySQL, Version 7.4.201.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 16/04/2018 11:35:51 AM
-- Server version: 5.5.5-10.1.31-MariaDB
-- Client version: 4.1
--

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

--
-- Set default database
--
USE almoeservice;

--
-- Drop table `engineers`
--
DROP TABLE IF EXISTS engineers;

--
-- Set default database
--
USE almoeservice;

--
-- Create table `engineers`
--
CREATE TABLE IF NOT EXISTS engineers (
  ID VARCHAR(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  NAME VARCHAR(100) NOT NULL,
  EMPID VARCHAR(25) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT 'NA',
  PRIMARY KEY (ID)
)
ENGINE = INNODB,
AVG_ROW_LENGTH = 4096,
CHARACTER SET utf8,
COLLATE utf8_unicode_ci;

--
-- Create index `NAME` on table `engineers`
--
ALTER TABLE engineers 
  ADD UNIQUE INDEX NAME(NAME);

DELIMITER $$

--
-- Create trigger `uuid_engineers`
--
CREATE 
	DEFINER = 'root'@'%'
TRIGGER IF NOT EXISTS uuid_engineers
	BEFORE INSERT
	ON engineers
	FOR EACH ROW
SET NEW.ID = UUID()
$$

DELIMITER ;

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
