USE almoeservice;

SELECT
  RECID,
  CPNO,
  ORDNO,
  ENDUSER,
  MACMODEL,
  SERIALNO,
  WEXPIRY,
  REMARKS,
  SALESMAN,
  INVNO,
  LPONO
FROM coverplusreg;

USE almoeservice;

INSERT INTO coverplusreg
(
  RECID
 ,CPNO
 ,ORDNO
 ,ENDUSER
 ,MACMODEL
 ,SERIALNO
 ,WEXPIRY
 ,REMARKS
 ,SALESMAN
 ,INVNO
 ,LPONO
)
VALUES
(
  0 -- RECID - BIGINT(20) NOT NULL
 ,'' -- CPNO - VARCHAR(255) NOT NULL
 ,'' -- ORDNO - VARCHAR(255) NOT NULL
 ,'' -- ENDUSER - VARCHAR(255) NOT NULL
 ,'' -- MACMODEL - VARCHAR(255) NOT NULL
 ,'' -- SERIALNO - VARCHAR(255) NOT NULL
 ,NOW() -- WEXPIRY - DATE NOT NULL
 ,'' -- REMARKS - VARCHAR(255)
 ,'' -- SALESMAN - VARCHAR(255)
 ,'' -- INVNO - VARCHAR(255)
 ,'' -- LPONO - VARCHAR(255)
);

USE almoeservice;

UPDATE coverplusreg 
SET
  CPNO = '' -- CPNO - VARCHAR(255) NOT NULL
 ,ORDNO = '' -- ORDNO - VARCHAR(255) NOT NULL
 ,ENDUSER = '' -- ENDUSER - VARCHAR(255) NOT NULL
 ,MACMODEL = '' -- MACMODEL - VARCHAR(255) NOT NULL
 ,SERIALNO = '' -- SERIALNO - VARCHAR(255) NOT NULL
 ,WEXPIRY = NOW() -- WEXPIRY - DATE NOT NULL
 ,REMARKS = '' -- REMARKS - VARCHAR(255)
 ,SALESMAN = '' -- SALESMAN - VARCHAR(255)
 ,INVNO = '' -- INVNO - VARCHAR(255)
 ,LPONO = '' -- LPONO - VARCHAR(255)
WHERE
  RECID = 0 -- RECID - BIGINT(20) NOT NULL
;

USE almoeservice;

DELETE FROM coverplusreg
WHERE
  RECID = 0 -- RECID - BIGINT(20) NOT NULL
;



USE almoeservice;

SET @in_CPNO = 'SCE0C0SD99SD9';
SET @in_ORDNO = '11244';
SET @in_ENDUSER = 'CHICAGO';
SET @in_MACMODEL = 'MFP T5200';
SET @in_SERIALNO = 'SR2043XXDD0S';
SET @in_WEXPIRY = '2040-12-31';
SET @in_REMARKS = 'NO REMARKS';
SET @in_SALESMAN = 'ABUL FASAL';
SET @in_INVNO = 'INV0001';
SET @in_LPONO = 'LPO00001';
CALL insertCoverPlusSingle(@in_CPNO, @in_ORDNO, @in_ENDUSER, @in_MACMODEL, @in_SERIALNO, @in_WEXPIRY, 
@in_REMARKS, @in_SALESMAN, @in_INVNO, @in_LPONO);
